#!/bin/bash
#SBATCH --job-name=gwfast_save_pop
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1        # Number of CPU cores per task
#SBATCH --partition=express
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

source /data/apps/linux-centos8-cascadelake/gcc-9.3.0/anaconda3-2020.07-i7qavhiohb2uwqs4eqjeefzx3kp5jqdu/etc/profile.d/conda.sh 

conda activate tides_gw

python scratch16-berti/tides_compas_veome/modern_tidal_interaction_models_dco_applications/population_gw_save_detection_posteriors.py
